In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = sns.load_dataset('titanic')

In [3]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [4]:
df.dropna(inplace=True)

In [5]:
df['survived'].unique()

array([1, 0], dtype=int64)

In [6]:
y = df['survived']
y.shape

(182,)

In [7]:
df['age'].unique()

array([38.  , 35.  , 54.  ,  4.  , 58.  , 34.  , 28.  , 19.  , 49.  ,
       65.  , 45.  , 29.  , 25.  , 23.  , 46.  , 71.  , 21.  , 47.  ,
       24.  , 32.5 , 37.  , 36.5 , 22.  , 61.  , 56.  , 50.  ,  1.  ,
        3.  , 44.  ,  2.  , 40.  , 31.  , 32.  , 62.  , 30.  , 52.  ,
       63.  , 36.  ,  0.92, 17.  , 18.  , 16.  , 45.5 , 41.  , 60.  ,
       27.  , 33.  , 14.  , 64.  , 48.  , 55.  , 39.  , 53.  , 42.  ,
       80.  , 15.  , 70.  ,  6.  , 51.  , 57.  , 43.  , 11.  , 26.  ])

In [8]:
X = df[['pclass', 'sex', 'age']]
X.head()

pclass     sex   age
1        1  female  38.0
3        1  female  35.0
6        1    male  54.0
10       3  female   4.0
11       1  female  58.0

In [9]:
from sklearn.preprocessing import LabelBinarizer

In [10]:
lb = LabelBinarizer()
X[['sex']] = lb.fit_transform(df[['sex']])
X.head()

C:\Users\office\Anaconda3\envs\Tree\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\Users\office\Anaconda3\envs\Tree\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


pclass  sex   age
1        1    0  38.0
3        1    0  35.0
6        1    1  54.0
10       3    0   4.0
11       1    0  58.0

In [11]:
X['sex'].value_counts()

1    94
0    88
Name: sex, dtype: int64

In [12]:
df['sex'].value_counts()

male      94
female    88
Name: sex, dtype: int64

In [13]:
X.describe()

pclass         sex         age
count  182.000000  182.000000  182.000000
mean     1.192308    0.516484   35.623187
std      0.516411    0.501107   15.671615
min      1.000000    0.000000    0.920000
25%      1.000000    0.000000   24.000000
50%      1.000000    1.000000   36.000000
75%      1.000000    1.000000   47.750000
max      3.000000    1.000000   80.000000

In [15]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import  RandomForestClassifier

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [17]:
def print_score(clf, X_train, X_test, y_train, y_test, train = True):
    '''
    To Print the accuracy score, Precision and recall score with confusion metrcis
    '''
    if train:
        '''
        Print the score of train datasets
        '''
        print("Accuracy score: \t{0:.4f}".format(accuracy_score(y_train, clf.predict(X_train))))
        print("classification_report: \n {} \n".format(classification_report(y_train, clf.predict(X_train))))
        print("confusion matrics: \n {} \n".format(confusion_matrix(y_train, clf.predict(X_train))))
        
        res = cross_val_score(clf, X_train, y_train, cv = 10, scoring = 'accuracy')
        print("Accuracy: \t {0:.4f} \nSD: \t\t{1:.4f}".format(np.mean(res), np.std(res)))
        
    elif train == False:
        '''
        Print the score of test sets
        '''
        print("Accuracy score: \t {0:.4f}".format(accuracy_score(y_test,clf.predict(X_test))))
        print("classification_report: \n {} \n".format(classification_report(y_test, clf.predict(X_test))))
        print("confusion matrics: \n {} \n".format(confusion_matrix(y_test, clf.predict(X_test))))
        
        

In [18]:
RandomForestClassifier?

In [19]:
clf = RandomForestClassifier(random_state=42)
clf.fit(X_train, y_train)

C:\Users\office\Anaconda3\envs\Tree\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [20]:
print_score(clf, X_train, X_test, y_train, y_test, train = True)

Accuracy score: 	0.9449
classification_report: 
               precision    recall  f1-score   support

           0       0.86      0.97      0.91        37
           1       0.99      0.93      0.96        90

   micro avg       0.94      0.94      0.94       127
   macro avg       0.92      0.95      0.94       127
weighted avg       0.95      0.94      0.95       127
 

confusion matrics: 
 [[36  1]
 [ 6 84]] 

Accuracy: 	 0.7801 
SD: 		0.0767


In [21]:
print_score(clf, X_train, X_test, y_train, y_test, train = False)

Accuracy score: 	 0.6545
classification_report: 
               precision    recall  f1-score   support

           0       0.56      0.64      0.60        22
           1       0.73      0.67      0.70        33

   micro avg       0.65      0.65      0.65        55
   macro avg       0.65      0.65      0.65        55
weighted avg       0.66      0.65      0.66        55
 

confusion matrics: 
 [[14  8]
 [11 22]] 



# Grid search

In [23]:
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline

In [26]:
clf.get_params()

{'bootstrap': True,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 10,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 42,
 'verbose': 0,
 'warm_start': False}

In [27]:
param = {'bootstrap': [True, False],
         'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, None],
         'max_features': ['auto', 'sqrt'],
         'min_samples_leaf': [1, 2, 4],
         'min_samples_split': [2, 5, 10],
         'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]}

In [29]:
grd_srch = GridSearchCV(estimator=clf, 
                        param_grid=param, 
                        n_jobs=-1, 
                        cv=5, 
                        verbose=1, 
                        scoring='accuracy')

In [30]:
grd_srch.fit(X_train, y_train)

Fitting 5 folds for each of 3960 candidates, totalling 19800 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   24.6s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  1.3min
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed:  2.7min
[Parallel(n_jobs=-1)]: Done 792 tasks      | elapsed:  4.8min
[Parallel(n_jobs=-1)]: Done 1242 tasks      | elapsed:  7.4min
[Parallel(n_jobs=-1)]: Done 1792 tasks      | elapsed: 10.6min
[Parallel(n_jobs=-1)]: Done 2442 tasks      | elapsed: 14.4min
[Parallel(n_jobs=-1)]: Done 3192 tasks      | elapsed: 18.8min
[Parallel(n_jobs=-1)]: Done 4042 tasks      | elapsed: 23.6min
[Parallel(n_jobs=-1)]: Done 4992 tasks      | elapsed: 29.0min
[Parallel(n_jobs=-1)]: Done 6042 tasks      | elapsed: 35.0min
[Parallel(n_jobs=-1)]: Done 7192 tasks      | elapsed: 41.6min
[Parallel(n_jobs=-1)]: Done 8442 tasks      | elapsed: 48.8min
[Parallel(n_jobs=-1)]: Done 9792 tasks      | elapsed: 56.5min
[Parallel(n_jobs=-1)]: Done 11242 tasks      |

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=-1,
       param_grid={'bootstrap': [True, False], 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, None], 'max_features': ['auto', 'sqrt'], 'min_samples_leaf': [1, 2, 4], 'min_samples_split': [2, 5, 10], 'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=1)

In [32]:
print_score(grd_srch, X_train, X_test, y_train, y_test, train = True)

Accuracy score: 	0.9449
classification_report: 
               precision    recall  f1-score   support

           0       0.89      0.92      0.91        37
           1       0.97      0.96      0.96        90

   micro avg       0.94      0.94      0.94       127
   macro avg       0.93      0.94      0.93       127
weighted avg       0.95      0.94      0.95       127
 

confusion matrics: 
 [[34  3]
 [ 4 86]] 

Fitting 5 folds for each of 3960 candidates, totalling 19800 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   19.7s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed:  2.7min
[Parallel(n_jobs=-1)]: Done 792 tasks      | elapsed:  5.1min
[Parallel(n_jobs=-1)]: Done 1242 tasks      | elapsed:  7.8min
[Parallel(n_jobs=-1)]: Done 1792 tasks      | elapsed: 11.1min
[Parallel(n_jobs=-1)]: Done 2442 tasks      | elapsed: 14.9min
[Parallel(n_jobs=-1)]: Done 3192 tasks      | elapsed: 19.3min
[Parallel(n_jobs=-1)]: Done 4042 tasks      | elapsed: 24.4min
[Parallel(n_jobs=-1)]: Done 4992 tasks      | elapsed: 30.0min
[Parallel(n_jobs=-1)]: Done 6042 tasks      | elapsed: 36.2min
[Parallel(n_jobs=-1)]: Done 7192 tasks      | elapsed: 42.9min
[Parallel(n_jobs=-1)]: Done 8442 tasks      | elapsed: 50.3min
[Parallel(n_jobs=-1)]: Done 9792 tasks      | elapsed: 58.3min
[Parallel(n_jobs=-1)]: Done 11242 tasks      |

Fitting 5 folds for each of 3960 candidates, totalling 19800 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   13.5s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed:  2.5min
[Parallel(n_jobs=-1)]: Done 792 tasks      | elapsed:  4.5min
[Parallel(n_jobs=-1)]: Done 1242 tasks      | elapsed:  7.1min
[Parallel(n_jobs=-1)]: Done 1792 tasks      | elapsed: 10.3min
[Parallel(n_jobs=-1)]: Done 2442 tasks      | elapsed: 14.0min
[Parallel(n_jobs=-1)]: Done 3192 tasks      | elapsed: 18.2min
[Parallel(n_jobs=-1)]: Done 4042 tasks      | elapsed: 23.0min
[Parallel(n_jobs=-1)]: Done 4992 tasks      | elapsed: 28.4min
[Parallel(n_jobs=-1)]: Done 6042 tasks      | elapsed: 34.4min
[Parallel(n_jobs=-1)]: Done 7192 tasks      | elapsed: 40.9min
[Parallel(n_jobs=-1)]: Done 8442 tasks      | elapsed: 48.0min
[Parallel(n_jobs=-1)]: Done 9792 tasks      | elapsed: 55.7min
[Parallel(n_jobs=-1)]: Done 11242 tasks      |

Fitting 5 folds for each of 3960 candidates, totalling 19800 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   13.0s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed:  2.5min
[Parallel(n_jobs=-1)]: Done 792 tasks      | elapsed:  4.4min
[Parallel(n_jobs=-1)]: Done 1242 tasks      | elapsed:  6.9min
[Parallel(n_jobs=-1)]: Done 1792 tasks      | elapsed: 10.0min
[Parallel(n_jobs=-1)]: Done 2442 tasks      | elapsed: 13.7min
[Parallel(n_jobs=-1)]: Done 3192 tasks      | elapsed: 17.9min
[Parallel(n_jobs=-1)]: Done 4042 tasks      | elapsed: 22.7min
[Parallel(n_jobs=-1)]: Done 4992 tasks      | elapsed: 28.1min
[Parallel(n_jobs=-1)]: Done 6042 tasks      | elapsed: 34.1min
[Parallel(n_jobs=-1)]: Done 7192 tasks      | elapsed: 40.7min
[Parallel(n_jobs=-1)]: Done 8442 tasks      | elapsed: 47.8min
[Parallel(n_jobs=-1)]: Done 9792 tasks      | elapsed: 55.5min
[Parallel(n_jobs=-1)]: Done 11242 tasks      |

Fitting 5 folds for each of 3960 candidates, totalling 19800 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   13.2s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed:  2.5min
[Parallel(n_jobs=-1)]: Done 792 tasks      | elapsed:  4.5min
[Parallel(n_jobs=-1)]: Done 1242 tasks      | elapsed:  7.1min
[Parallel(n_jobs=-1)]: Done 1792 tasks      | elapsed: 10.2min
[Parallel(n_jobs=-1)]: Done 2442 tasks      | elapsed: 14.0min
[Parallel(n_jobs=-1)]: Done 3192 tasks      | elapsed: 18.3min
[Parallel(n_jobs=-1)]: Done 4042 tasks      | elapsed: 23.3min
[Parallel(n_jobs=-1)]: Done 4992 tasks      | elapsed: 28.7min
[Parallel(n_jobs=-1)]: Done 6042 tasks      | elapsed: 34.7min
[Parallel(n_jobs=-1)]: Done 7192 tasks      | elapsed: 41.3min
[Parallel(n_jobs=-1)]: Done 8442 tasks      | elapsed: 48.4min
[Parallel(n_jobs=-1)]: Done 9792 tasks      | elapsed: 56.1min
[Parallel(n_jobs=-1)]: Done 11242 tasks      |

Fitting 5 folds for each of 3960 candidates, totalling 19800 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   13.2s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed:  2.5min
[Parallel(n_jobs=-1)]: Done 792 tasks      | elapsed:  4.5min
[Parallel(n_jobs=-1)]: Done 1242 tasks      | elapsed:  7.1min
[Parallel(n_jobs=-1)]: Done 1792 tasks      | elapsed: 10.2min
[Parallel(n_jobs=-1)]: Done 2442 tasks      | elapsed: 13.9min
[Parallel(n_jobs=-1)]: Done 3192 tasks      | elapsed: 18.2min
[Parallel(n_jobs=-1)]: Done 4042 tasks      | elapsed: 23.1min
[Parallel(n_jobs=-1)]: Done 4992 tasks      | elapsed: 28.5min
[Parallel(n_jobs=-1)]: Done 6042 tasks      | elapsed: 34.5min
[Parallel(n_jobs=-1)]: Done 7192 tasks      | elapsed: 41.1min
[Parallel(n_jobs=-1)]: Done 8442 tasks      | elapsed: 48.1min
[Parallel(n_jobs=-1)]: Done 9792 tasks      | elapsed: 55.7min
[Parallel(n_jobs=-1)]: Done 11242 tasks      |

Fitting 5 folds for each of 3960 candidates, totalling 19800 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   13.1s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed:  2.5min
[Parallel(n_jobs=-1)]: Done 792 tasks      | elapsed:  4.4min
[Parallel(n_jobs=-1)]: Done 1242 tasks      | elapsed:  7.0min
[Parallel(n_jobs=-1)]: Done 1792 tasks      | elapsed: 10.1min
[Parallel(n_jobs=-1)]: Done 2442 tasks      | elapsed: 13.7min
[Parallel(n_jobs=-1)]: Done 3192 tasks      | elapsed: 17.9min
[Parallel(n_jobs=-1)]: Done 4042 tasks      | elapsed: 22.7min
[Parallel(n_jobs=-1)]: Done 4992 tasks      | elapsed: 28.0min
[Parallel(n_jobs=-1)]: Done 6042 tasks      | elapsed: 33.9min
[Parallel(n_jobs=-1)]: Done 7192 tasks      | elapsed: 40.3min
[Parallel(n_jobs=-1)]: Done 8442 tasks      | elapsed: 47.4min
[Parallel(n_jobs=-1)]: Done 9792 tasks      | elapsed: 54.9min
[Parallel(n_jobs=-1)]: Done 11242 tasks      |

Fitting 5 folds for each of 3960 candidates, totalling 19800 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   13.1s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed:  2.5min
[Parallel(n_jobs=-1)]: Done 792 tasks      | elapsed:  4.4min
[Parallel(n_jobs=-1)]: Done 1242 tasks      | elapsed:  7.0min
[Parallel(n_jobs=-1)]: Done 1792 tasks      | elapsed: 10.0min
[Parallel(n_jobs=-1)]: Done 2442 tasks      | elapsed: 13.7min
[Parallel(n_jobs=-1)]: Done 3192 tasks      | elapsed: 17.9min
[Parallel(n_jobs=-1)]: Done 4042 tasks      | elapsed: 22.9min
[Parallel(n_jobs=-1)]: Done 4992 tasks      | elapsed: 29.4min
[Parallel(n_jobs=-1)]: Done 6042 tasks      | elapsed: 36.9min
[Parallel(n_jobs=-1)]: Done 7192 tasks      | elapsed: 44.0min
[Parallel(n_jobs=-1)]: Done 8442 tasks      | elapsed: 51.5min
[Parallel(n_jobs=-1)]: Done 9792 tasks      | elapsed: 60.0min
[Parallel(n_jobs=-1)]: Done 11242 tasks      |

Fitting 5 folds for each of 3960 candidates, totalling 19800 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   15.0s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed:  2.7min
[Parallel(n_jobs=-1)]: Done 792 tasks      | elapsed:  4.8min
[Parallel(n_jobs=-1)]: Done 1242 tasks      | elapsed:  7.5min
[Parallel(n_jobs=-1)]: Done 1792 tasks      | elapsed: 10.8min
[Parallel(n_jobs=-1)]: Done 2442 tasks      | elapsed: 14.7min
[Parallel(n_jobs=-1)]: Done 3192 tasks      | elapsed: 19.7min
[Parallel(n_jobs=-1)]: Done 4042 tasks      | elapsed: 25.3min
[Parallel(n_jobs=-1)]: Done 4992 tasks      | elapsed: 30.8min
[Parallel(n_jobs=-1)]: Done 6042 tasks      | elapsed: 37.3min
[Parallel(n_jobs=-1)]: Done 7192 tasks      | elapsed: 44.5min
[Parallel(n_jobs=-1)]: Done 8442 tasks      | elapsed: 52.4min
[Parallel(n_jobs=-1)]: Done 9792 tasks      | elapsed: 61.3min
[Parallel(n_jobs=-1)]: Done 11242 tasks      |

Fitting 5 folds for each of 3960 candidates, totalling 19800 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   13.5s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed:  2.5min
[Parallel(n_jobs=-1)]: Done 792 tasks      | elapsed:  4.6min
[Parallel(n_jobs=-1)]: Done 1242 tasks      | elapsed:  7.2min
[Parallel(n_jobs=-1)]: Done 1792 tasks      | elapsed: 10.4min
[Parallel(n_jobs=-1)]: Done 2442 tasks      | elapsed: 14.1min
[Parallel(n_jobs=-1)]: Done 3192 tasks      | elapsed: 18.5min
[Parallel(n_jobs=-1)]: Done 4042 tasks      | elapsed: 23.4min
[Parallel(n_jobs=-1)]: Done 4992 tasks      | elapsed: 28.9min
[Parallel(n_jobs=-1)]: Done 6042 tasks      | elapsed: 34.9min
[Parallel(n_jobs=-1)]: Done 7192 tasks      | elapsed: 41.6min
[Parallel(n_jobs=-1)]: Done 8442 tasks      | elapsed: 48.9min
[Parallel(n_jobs=-1)]: Done 9792 tasks      | elapsed: 56.7min
[Parallel(n_jobs=-1)]: Done 11242 tasks      |

Fitting 5 folds for each of 3960 candidates, totalling 19800 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   13.4s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed:  2.5min
[Parallel(n_jobs=-1)]: Done 792 tasks      | elapsed:  4.5min
[Parallel(n_jobs=-1)]: Done 1242 tasks      | elapsed:  7.1min
[Parallel(n_jobs=-1)]: Done 1792 tasks      | elapsed: 10.3min
[Parallel(n_jobs=-1)]: Done 2442 tasks      | elapsed: 14.4min
[Parallel(n_jobs=-1)]: Done 3192 tasks      | elapsed: 19.3min
[Parallel(n_jobs=-1)]: Done 4042 tasks      | elapsed: 24.3min
[Parallel(n_jobs=-1)]: Done 4992 tasks      | elapsed: 29.8min
[Parallel(n_jobs=-1)]: Done 6042 tasks      | elapsed: 35.8min
[Parallel(n_jobs=-1)]: Done 7192 tasks      | elapsed: 42.4min
[Parallel(n_jobs=-1)]: Done 8442 tasks      | elapsed: 49.7min
[Parallel(n_jobs=-1)]: Done 9792 tasks      | elapsed: 57.4min
[Parallel(n_jobs=-1)]: Done 11242 tasks      |

Accuracy: 	 0.7654 
SD: 		0.1015


In [33]:
print_score(grd_srch, X_train, X_test, y_train, y_test, train = False)

Accuracy score: 	 0.7636
classification_report: 
               precision    recall  f1-score   support

           0       0.74      0.64      0.68        22
           1       0.78      0.85      0.81        33

   micro avg       0.76      0.76      0.76        55
   macro avg       0.76      0.74      0.75        55
weighted avg       0.76      0.76      0.76        55
 

confusion matrics: 
 [[14  8]
 [ 5 28]] 

